// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {indentation, trackIndent} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fQ]QROOPbOPOOOgQRO'#C_OOQP'#Cn'#CnOOQP'#Cd'#CdQ]QROOPoOQO)C>_OOQP'#Ck'#CkO}QRO,58yOOQP-E6b-E6bPOOO'#Cc'#CcPoOQO/'3yPOOO/'3y/'3yO]QRO'#CbOOQP1G.g1G.gPOOO-E6a-E6aPOOO49)e49)eO!`QRO,58|OOQP1G.h1G.h",
  stateData: "!k~O^OSPOS[PQ~OSQO~O[UO~O`VOaVO~OPYO^YO`VOaVO~OY]OSRaXRaZRaaRa~OSQOZbOabO~O",
  goto: "!^cPPPdPdjmsPPPPPP}PP!WXROT]aR^WQZUR_ZQTOSXTaRa]QWQQ[UR`ZXSOT]a",
  nodeNames: "⚠ Comment Tree Atom Identifier Section Block",
  maxTerm: 18,
  context: trackIndent,
  skippedNodes: [0,1,7],
  repeatNodeCount: 2,
  tokenData: "#^~RXXYnYZypqnst!O!Q![!v!c!}!v#R#S!v#T#o!v~~#X~sQ^~XYnpqn~!OO`~~!RSOY!_Z;'S!_;'S;=`!p<%lO!_~!dSP~OY!_Z;'S!_;'S;=`!p<%lO!_~!sP;=`<%l!_~!{SS~!Q![!v!c!}!v#R#S!v#T#o!v~#^Oa~",
  tokenizers: [indentation, 0],
  topRules: {"Tree":[0,2]},
  tokenPrec: 0
})
