// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  indent = 10,
  dedent = 11,
  blankLineStart = 12,
  Comment = 1,
  Tree = 2,
  Identifier = 4,
  Block = 6
